module.exports = {
  1: {
    id: 1,
    name: '姜祖',
    birthYear: 1,
    generation: 0,
    children: [2, 3, 5, 11],
    age: 128,
    maxAge: 100,
    deathYear: 129,
  },
  2: {
    id: 2,
    name: '姜宇質',
    generation: 1,
    birthYear: 26,
    children: [4, 6, 12, 20],
    age: 119,
    maxAge: 100,
    parentId: 1,
    parentName: '姜祖',
    deathYear: 145,
  },
  3: {
    id: 3,
    name: '姜宇臿',
    generation: 1,
    birthYear: 52,
    children: [7, 10, 31, 62],
    age: 137,
    maxAge: 100,
    parentId: 1,
    parentName: '姜祖',
    deathYear: 189,
  },
  4: {
    id: 4,
    name: '姜宙媽',
    generation: 2,
    birthYear: 53,
    children: [8, 9, 17, 37],
    age: 113,
    maxAge: 100,
    parentId: 2,
    parentName: '姜宇質',
    deathYear: 166,
  },
  5: {
    id: 5,
    name: '姜宇慸',
    generation: 1,
    birthYear: 72,
    children: [16, 18, 40, 77],
    age: 129,
    maxAge: 100,
    parentId: 1,
    parentName: '姜祖',
  },
  6: {
    id: 6,
    name: '姜宙咉',
    generation: 2,
    birthYear: 83,
    children: [14, 23, 39, 69],
    age: 118,
    maxAge: 100,
    parentId: 2,
    parentName: '姜宇質',
  },
  7: {
    id: 7,
    name: '姜宙冕',
    generation: 2,
    birthYear: 83,
    children: [15, 30, 47, 80],
    age: 118,
    maxAge: 100,
    parentId: 3,
    parentName: '姜宇臿',
  },
  8: {
    id: 8,
    name: '姜万癧',
    generation: 3,
    birthYear: 84,
    children: [13, 21, 32, 64],
    age: 117,
    maxAge: 100,
    parentId: 4,
    parentName: '姜宙媽',
  },
  9: {
    id: 9,
    name: '姜万䆙',
    generation: 3,
    birthYear: 104,
    children: [],
    age: 38,
    maxAge: 100,
    parentId: 4,
    parentName: '姜宙媽',
    deathYear: 142,
  },
  10: {
    id: 10,
    name: '姜宙倬',
    generation: 2,
    birthYear: 105,
    children: [22, 52, 78],
    age: 96,
    maxAge: 100,
    parentId: 3,
    parentName: '姜宇臿',
  },
  11: {
    id: 11,
    name: '姜宇喸',
    generation: 1,
    birthYear: 107,
    children: [19, 33, 58],
    age: 94,
    maxAge: 100,
    parentId: 1,
    parentName: '姜祖',
  },
  12: {
    id: 12,
    name: '姜宙荦',
    generation: 2,
    birthYear: 109,
    children: [26, 35],
    age: 92,
    maxAge: 100,
    parentId: 2,
    parentName: '姜宇質',
  },
  13: {
    id: 13,
    name: '姜物亳',
    generation: 4,
    birthYear: 109,
    children: [28, 48],
    age: 92,
    maxAge: 100,
    parentId: 8,
    parentName: '姜万癧',
  },
  14: {
    id: 14,
    name: '姜万鎾',
    generation: 3,
    birthYear: 111,
    children: [24, 34],
    age: 90,
    maxAge: 100,
    parentId: 6,
    parentName: '姜宙咉',
  },
  15: {
    id: 15,
    name: '姜万䳖',
    generation: 3,
    birthYear: 111,
    children: [27, 67, 81],
    age: 90,
    maxAge: 100,
    parentId: 7,
    parentName: '姜宙冕',
  },
  16: {
    id: 16,
    name: '姜宙䂸',
    generation: 2,
    birthYear: 113,
    children: [25, 50],
    age: 88,
    maxAge: 100,
    parentId: 5,
    parentName: '姜宇慸',
  },
  17: {
    id: 17,
    name: '姜万緆',
    generation: 3,
    birthYear: 120,
    children: [36, 49, 72],
    age: 81,
    maxAge: 100,
    parentId: 4,
    parentName: '姜宙媽',
  },
  18: {
    id: 18,
    name: '姜宙嗰',
    generation: 2,
    birthYear: 126,
    children: [29, 59],
    age: 75,
    maxAge: 100,
    parentId: 5,
    parentName: '姜宇慸',
  },
  19: {
    id: 19,
    name: '姜宙笙',
    generation: 2,
    birthYear: 132,
    children: [38, 53],
    age: 69,
    maxAge: 100,
    parentId: 11,
    parentName: '姜宇喸',
  },
  20: {
    id: 20,
    name: '姜宙寋',
    generation: 2,
    birthYear: 133,
    children: [41, 65],
    age: 68,
    maxAge: 100,
    parentId: 2,
    parentName: '姜宇質',
  },
  21: {
    id: 21,
    name: '姜物䒇',
    generation: 4,
    birthYear: 136,
    children: [43],
    age: 65,
    maxAge: 100,
    parentId: 8,
    parentName: '姜万癧',
  },
  22: {
    id: 22,
    name: '姜万㙦',
    generation: 3,
    birthYear: 138,
    children: [45],
    age: 63,
    maxAge: 100,
    parentId: 10,
    parentName: '姜宙倬',
  },
  23: {
    id: 23,
    name: '姜万鯃',
    generation: 3,
    birthYear: 139,
    children: [68],
    age: 62,
    maxAge: 100,
    parentId: 6,
    parentName: '姜宙咉',
  },
  24: {
    id: 24,
    name: '姜物㞄',
    generation: 4,
    birthYear: 139,
    children: [51],
    age: 62,
    maxAge: 100,
    parentId: 14,
    parentName: '姜万鎾',
  },
  25: {
    id: 25,
    name: '姜万㗛',
    generation: 3,
    birthYear: 139,
    children: [44],
    age: 62,
    maxAge: 100,
    parentId: 16,
    parentName: '姜宙䂸',
  },
  26: {
    id: 26,
    name: '姜万栟',
    generation: 3,
    birthYear: 141,
    children: [42],
    age: 60,
    maxAge: 100,
    parentId: 12,
    parentName: '姜宙荦',
  },
  27: {
    id: 27,
    name: '姜物賻',
    generation: 4,
    birthYear: 143,
    children: [54, 83],
    age: 58,
    maxAge: 100,
    parentId: 15,
    parentName: '姜万䳖',
  },
  28: {
    id: 28,
    name: '姜位㷈',
    generation: 5,
    birthYear: 145,
    children: [55],
    age: 56,
    maxAge: 100,
    parentId: 13,
    parentName: '姜物亳',
  },
  29: {
    id: 29,
    name: '姜万偆',
    generation: 3,
    birthYear: 149,
    children: [56],
    age: 52,
    maxAge: 100,
    parentId: 18,
    parentName: '姜宙嗰',
  },
  30: {
    id: 30,
    name: '姜万㻥',
    generation: 3,
    birthYear: 150,
    children: [46],
    age: 51,
    maxAge: 100,
    parentId: 7,
    parentName: '姜宙冕',
  },
  31: {
    id: 31,
    name: '姜宙䜱',
    generation: 2,
    birthYear: 151,
    children: [60, 84],
    age: 50,
    maxAge: 100,
    parentId: 3,
    parentName: '姜宇臿',
  },
  32: {
    id: 32,
    name: '姜物铢',
    generation: 4,
    birthYear: 152,
    children: [70],
    age: 49,
    maxAge: 100,
    parentId: 8,
    parentName: '姜万癧',
  },
  33: {
    id: 33,
    name: '姜宙䁔',
    generation: 2,
    birthYear: 153,
    children: [73],
    age: 48,
    maxAge: 100,
    parentId: 11,
    parentName: '姜宇喸',
  },
  34: {
    id: 34,
    name: '姜物鵡',
    generation: 4,
    birthYear: 155,
    children: [66],
    age: 46,
    maxAge: 100,
    parentId: 14,
    parentName: '姜万鎾',
  },
  35: {
    id: 35,
    name: '姜万餲',
    generation: 3,
    birthYear: 157,
    children: [63],
    age: 44,
    maxAge: 100,
    parentId: 12,
    parentName: '姜宙荦',
  },
  36: {
    id: 36,
    name: '姜物莏',
    generation: 4,
    birthYear: 157,
    children: [71],
    age: 44,
    maxAge: 100,
    parentId: 17,
    parentName: '姜万緆',
  },
  37: {
    id: 37,
    name: '姜万煉',
    generation: 3,
    birthYear: 158,
    children: [57],
    age: 43,
    maxAge: 100,
    parentId: 4,
    parentName: '姜宙媽',
  },
  38: {
    id: 38,
    name: '姜万迅',
    generation: 3,
    birthYear: 160,
    children: [61],
    age: 41,
    maxAge: 100,
    parentId: 19,
    parentName: '姜宙笙',
  },
  39: {
    id: 39,
    name: '姜万立',
    generation: 3,
    birthYear: 161,
    children: [82],
    age: 40,
    maxAge: 100,
    parentId: 6,
    parentName: '姜宙咉',
  },
  40: {
    id: 40,
    name: '姜宙㑶',
    generation: 2,
    birthYear: 163,
    children: [75],
    age: 38,
    maxAge: 100,
    parentId: 5,
    parentName: '姜宇慸',
  },
  41: {
    id: 41,
    name: '姜万㮎',
    generation: 3,
    birthYear: 163,
    children: [79],
    age: 38,
    maxAge: 100,
    parentId: 20,
    parentName: '姜宙寋',
  },
  42: {
    id: 42,
    name: '姜物偨',
    generation: 4,
    birthYear: 166,
    children: [],
    age: 35,
    maxAge: 100,
    parentId: 26,
    parentName: '姜万栟',
  },
  43: {
    id: 43,
    name: '姜位䤴',
    generation: 5,
    birthYear: 167,
    children: [85],
    age: 34,
    maxAge: 100,
    parentId: 21,
    parentName: '姜物䒇',
  },
  44: {
    id: 44,
    name: '姜物䬌',
    generation: 4,
    birthYear: 168,
    children: [76],
    age: 33,
    maxAge: 100,
    parentId: 25,
    parentName: '姜万㗛',
  },
  45: {
    id: 45,
    name: '姜物㳿',
    generation: 4,
    birthYear: 171,
    children: [],
    age: 30,
    maxAge: 100,
    parentId: 22,
    parentName: '姜万㙦',
  },
  46: {
    id: 46,
    name: '姜物䈋',
    generation: 4,
    birthYear: 171,
    children: [74],
    age: 30,
    maxAge: 100,
    parentId: 30,
    parentName: '姜万㻥',
  },
  47: {
    id: 47,
    name: '姜万㵰',
    generation: 3,
    birthYear: 172,
    children: [],
    age: 29,
    maxAge: 100,
    parentId: 7,
    parentName: '姜宙冕',
  },
  48: {
    id: 48,
    name: '姜位橫',
    generation: 5,
    birthYear: 172,
    children: [],
    age: 29,
    maxAge: 100,
    parentId: 13,
    parentName: '姜物亳',
  },
  49: {
    id: 49,
    name: '姜物㥈',
    generation: 4,
    birthYear: 174,
    children: [],
    age: 27,
    maxAge: 100,
    parentId: 17,
    parentName: '姜万緆',
  },
  50: {
    id: 50,
    name: '姜万东',
    generation: 3,
    birthYear: 176,
    children: [86],
    age: 25,
    maxAge: 100,
    parentId: 16,
    parentName: '姜宙䂸',
  },
  51: {
    id: 51,
    name: '姜位贒',
    generation: 5,
    birthYear: 177,
    children: [],
    age: 24,
    maxAge: 100,
    parentId: 24,
    parentName: '姜物㞄',
  },
  52: {
    id: 52,
    name: '姜万昙',
    generation: 3,
    birthYear: 178,
    children: [],
    age: 23,
    maxAge: 100,
    parentId: 10,
    parentName: '姜宙倬',
  },
  53: {
    id: 53,
    name: '姜万甚',
    generation: 3,
    birthYear: 178,
    children: [],
    age: 23,
    maxAge: 100,
    parentId: 19,
    parentName: '姜宙笙',
  },
  54: {
    id: 54,
    name: '姜位䗄',
    generation: 5,
    birthYear: 180,
    children: [],
    age: 21,
    maxAge: 100,
    parentId: 27,
    parentName: '姜物賻',
  },
  55: {
    id: 55,
    name: '姜面䵵',
    generation: 6,
    birthYear: 180,
    children: [],
    age: 21,
    maxAge: 100,
    parentId: 28,
    parentName: '姜位㷈',
  },
  56: {
    id: 56,
    name: '姜物踲',
    generation: 4,
    birthYear: 180,
    children: [],
    age: 21,
    maxAge: 100,
    parentId: 29,
    parentName: '姜万偆',
  },
  57: {
    id: 57,
    name: '姜物跮',
    generation: 4,
    birthYear: 180,
    children: [],
    age: 21,
    maxAge: 100,
    parentId: 37,
    parentName: '姜万煉',
  },
  58: {
    id: 58,
    name: '姜宙刲',
    generation: 2,
    birthYear: 181,
    children: [],
    age: 20,
    maxAge: 100,
    parentId: 11,
    parentName: '姜宇喸',
  },
  59: {
    id: 59,
    name: '姜万迌',
    generation: 3,
    birthYear: 182,
    children: [],
    age: 19,
    maxAge: 100,
    parentId: 18,
    parentName: '姜宙嗰',
  },
  60: {
    id: 60,
    name: '姜万㠶',
    generation: 3,
    birthYear: 182,
    children: [],
    age: 19,
    maxAge: 100,
    parentId: 31,
    parentName: '姜宙䜱',
  },
  61: {
    id: 61,
    name: '姜物䎼',
    generation: 4,
    birthYear: 182,
    children: [],
    age: 19,
    maxAge: 100,
    parentId: 38,
    parentName: '姜万迅',
  },
  62: {
    id: 62,
    name: '姜宙督',
    generation: 2,
    birthYear: 184,
    children: [],
    age: 17,
    maxAge: 100,
    parentId: 3,
    parentName: '姜宇臿',
  },
  63: {
    id: 63,
    name: '姜物婺',
    generation: 4,
    birthYear: 187,
    children: [],
    age: 14,
    maxAge: 100,
    parentId: 35,
    parentName: '姜万餲',
  },
  64: {
    id: 64,
    name: '姜物楥',
    generation: 4,
    birthYear: 188,
    children: [],
    age: 13,
    maxAge: 100,
    parentId: 8,
    parentName: '姜万癧',
  },
  65: {
    id: 65,
    name: '姜万孠',
    generation: 3,
    birthYear: 188,
    children: [],
    age: 13,
    maxAge: 100,
    parentId: 20,
    parentName: '姜宙寋',
  },
  66: {
    id: 66,
    name: '姜位衐',
    generation: 5,
    birthYear: 189,
    children: [],
    age: 12,
    maxAge: 100,
    parentId: 34,
    parentName: '姜物鵡',
  },
  67: {
    id: 67,
    name: '姜物㾛',
    generation: 4,
    birthYear: 190,
    children: [],
    age: 11,
    maxAge: 100,
    parentId: 15,
    parentName: '姜万䳖',
  },
  68: {
    id: 68,
    name: '姜物虛',
    generation: 4,
    birthYear: 190,
    children: [],
    age: 11,
    maxAge: 100,
    parentId: 23,
    parentName: '姜万鯃',
  },
  69: {
    id: 69,
    name: '姜万擄',
    generation: 3,
    birthYear: 191,
    children: [],
    age: 10,
    maxAge: 100,
    parentId: 6,
    parentName: '姜宙咉',
  },
  70: {
    id: 70,
    name: '姜位輋',
    generation: 5,
    birthYear: 192,
    children: [],
    age: 9,
    maxAge: 100,
    parentId: 32,
    parentName: '姜物铢',
  },
  71: {
    id: 71,
    name: '姜位灈',
    generation: 5,
    birthYear: 193,
    children: [],
    age: 8,
    maxAge: 100,
    parentId: 36,
    parentName: '姜物莏',
  },
  72: {
    id: 72,
    name: '姜物摤',
    generation: 4,
    birthYear: 195,
    children: [],
    age: 6,
    maxAge: 100,
    parentId: 17,
    parentName: '姜万緆',
  },
  73: {
    id: 73,
    name: '姜万莠',
    generation: 3,
    birthYear: 195,
    children: [],
    age: 6,
    maxAge: 100,
    parentId: 33,
    parentName: '姜宙䁔',
  },
  74: {
    id: 74,
    name: '姜位蘁',
    generation: 5,
    birthYear: 195,
    children: [],
    age: 6,
    maxAge: 100,
    parentId: 46,
    parentName: '姜物䈋',
  },
  75: {
    id: 75,
    name: '姜万笜',
    generation: 3,
    birthYear: 196,
    children: [],
    age: 5,
    maxAge: 100,
    parentId: 40,
    parentName: '姜宙㑶',
  },
  76: {
    id: 76,
    name: '姜位傒',
    generation: 5,
    birthYear: 196,
    children: [],
    age: 5,
    maxAge: 100,
    parentId: 44,
    parentName: '姜物䬌',
  },
  77: {
    id: 77,
    name: '姜宙鋈',
    generation: 2,
    birthYear: 197,
    children: [],
    age: 4,
    maxAge: 100,
    parentId: 5,
    parentName: '姜宇慸',
  },
  78: {
    id: 78,
    name: '姜万晩',
    generation: 3,
    birthYear: 197,
    children: [],
    age: 4,
    maxAge: 100,
    parentId: 10,
    parentName: '姜宙倬',
  },
  79: {
    id: 79,
    name: '姜物磝',
    generation: 4,
    birthYear: 197,
    children: [],
    age: 4,
    maxAge: 100,
    parentId: 41,
    parentName: '姜万㮎',
  },
  80: {
    id: 80,
    name: '姜万䰡',
    generation: 3,
    birthYear: 199,
    children: [],
    age: 2,
    maxAge: 100,
    parentId: 7,
    parentName: '姜宙冕',
  },
  81: {
    id: 81,
    name: '姜物攓',
    generation: 4,
    birthYear: 199,
    children: [],
    age: 2,
    maxAge: 100,
    parentId: 15,
    parentName: '姜万䳖',
  },
  82: {
    id: 82,
    name: '姜物䂀',
    generation: 4,
    birthYear: 199,
    children: [],
    age: 2,
    maxAge: 100,
    parentId: 39,
    parentName: '姜万立',
  },
  83: {
    id: 83,
    name: '姜位擤',
    generation: 5,
    birthYear: 200,
    children: [],
    age: 1,
    maxAge: 100,
    parentId: 27,
    parentName: '姜物賻',
  },
  84: {
    id: 84,
    name: '姜万宍',
    generation: 3,
    birthYear: 200,
    children: [],
    age: 1,
    maxAge: 100,
    parentId: 31,
    parentName: '姜宙䜱',
  },
  85: {
    id: 85,
    name: '姜面捋',
    generation: 6,
    birthYear: 200,
    children: [],
    age: 1,
    maxAge: 100,
    parentId: 43,
    parentName: '姜位䤴',
  },
  86: {
    id: 86,
    name: '姜物鮉',
    generation: 4,
    birthYear: 200,
    children: [],
    age: 1,
    maxAge: 100,
    parentId: 50,
    parentName: '姜万东',
  },
};
