export default [
  {
    name: "VV Engineering Challenge #2",
    code: "59e565c95008d",
    heng: [
      "(X|Y|Z).*\\1.*\\1",
      "[^XYZ]*[XYZ]*",
      "(.).*(.).*\\2.*\\1",
      "[^X]*X+[^X]*",
      "([^X]|XXY)*",
      "[ABCD]*YO[EFGH]*",
      "[^RX](R|XX)*",
      "(...?)\\1*",
      ".*Y.*Z+",
    ],
    zuoxie: [
      ".*RZ.*",
      "(HY|RM|FX|EH)*",
      "X*F.*G.*H.*",
      "Y.*N.*",
      "(XX|YY|ZZ)*[XYZ]{2}.",
      "(.)(.).*\\1.*\\2.*\\2\\1",
      "[BMX]*",
      "[^DB]*DB[^DB]*",
      "[^A]B[^C]D[^E]",
    ],
    youxie: [
      "[^ABE]*BE[^ABE]*Z.*",
      ".*[BD]+",
      "[^A]*A[^A]*",
      ".*MM.*",
      "[^XO]*XO[^XO]*OX[^XO]*(.)\\1",
      "(.+).*\\1",
      ".*X.X.X.*",
      "H+(..)\\1.*",
      ".*(MR|CH|RF)[^X]*",
    ],
  },
  {
    name: "From 2013 MIT Mystery Hunt, by Dan Gulotta, Palmer Mebane",
    code: "8cbea27f-c4c5-4d11-a509-6a622ba01107",
    heng: [
      ".*H.*H.*",
      "(DI|NS|TH|OM)*",
      "F.*[AO].*[AO].*",
      "(O|RHH|MM)*",
      ".*",
      "C*MC(CCC|MM)*",
      "[^C]*[^R]*III.*",
      "(...?)\\1*",
      "([^X]|XCC)*",
      "(RR|HHH)*.?",
      "N.*X.X.X.*E",
      "R*D*M*",
      ".(C|HH)*",
    ],
    zuoxie: [
      ".*SE.*UE.*",
      ".*LR.*RL.*",
      ".*OXR.*",
      "([^EMC]|EM)*",
      "(HHX|[^HX])*",
      ".*PRR.*DDC.*",
      ".*",
      "[AM]*CM(RC)*R?",
      "([^MC]|MM|CC)*",
      "(E|CR|MN)*",
      "P+(..)\\1.*",
      "[CHMNOR]*I[CHMNOR]*",
      "(ND|ET|IN)[^X]*",
    ],
    youxie: [
      ".*G.*V.*H.*",
      "[CR]*",
      ".*XEXM*",
      ".*DD.*CCM.*",
      ".*XHCR.*X.*",
      ".*(.)(.)(.)(.)\\4\\3\\2\\1.*",
      ".*(IN|SE|HI)",
      "[^C]*MMM[^C]*",
      ".*(.)C\\1X\\1.*",
      "[CEIMU]*OH[AEMOR]*",
      "(RX|[^R])*",
      "[^M]*M[^M]*",
      "(S|MM|HHH)*",
    ],
  },
  {
    name: "The Matrix",
    code: "56a7569259530",
    heng: [
      "(?!.*(.).*\\1.*)(?=^[AOUTY ]+$)[^\\s].*[UO]*\\W.+A.*",
      ".*E.*\\W.*O.*E.*S",
      "(?=^[OELHT ]+$)^(\\W)H..\\w.*\\1.*H.*",
      "(?!.*(\\w).*\\1.*)(?=^[AEOHRSW ]+$)^E\\W.*\\W.*",
      "(?=^[ABDEGIRT ]+$)(.)\\1.*\\W.*\\W.",
      "(?!.*L.*).*(D),\\s.*\\1EE.\\s.*",
      "(?!.*(\\w).*\\1.*)(?=^[AIUNSTY, ]+$)[UO]*\\W.*A.*\\W.*",
      "\\s.*LL\\s.*[EFW]..",
      "D.*LA.*D\\s",
      "(?!.*(\\w).*\\1.*)(?=^[IOUHY\\s]+$).*[UO]*\\W.*H.*",
      "(?!.*(.).*\\1.*)(?=^[EOHTW\\s]+$)[UO].*\\W.*H.*",
    ],
    zuoxie: [
      "(?!.*(.).*\\1.*)(?=^[EOHN, \\s]+$).*",
      "(?!.*(.).*\\1.*)(?=^[AODHNY\\s]+$).*",
      "(?=^.{3}\\w+$)(?!.*(\\w).*\\1.*)(?=^[AIUNWT\\s]+$).*",
      "(?!.*(\\w).*\\1.*)(?=^[ADHOPR\\s]+$).*",
      ".T.(E)\\1\\w.*",
      "(?=^[AELORW ]+$)(.)(.).*\\2\\1.*",
      "(?=^[EIODT ]+$).*(T)(O)(E).*\\2.*\\1.*(I).*\\3.*\\4.*",
      "(?!.*(\\w).*\\1.*)(?=^[DGHLSPT\\s]+$).*H.*S\\S.",
      "(?!.*(\\w).*\\1.*)(?=^[IOUS,\\s]+$).*U\\W\\w.*I.*",
      "(?!.*(.).*\\1.*)(?=^[EOUBDH\\s]+$).*[UO]*\\W.*B.*",
      "(?!.*(.).*\\1.*)(?=^[EBKNY\\s]+$).*K*\\W.*E.*",
    ],
    youxie: [
      "(?!.*(.).*\\1.*)(?=^[IOUDN\\s]+$)[UO].*\\W.*N.*",
      "(?!.*(\\w).*\\1.*)(?=^[BDEPW\\s]+$)W.*[E]*\\W.*B.*",
      "(?!.*(.).*\\1.*)(?=^[BEIRSY,\\s]+$)\\sY.*,.*B.*",
      "(?=^[IOLT ]+$)T\\S.*LLT.*\\S.{2}",
      "(?=^[ADULHKST]+$).*H.*A.*A.*H.*",
      "(E).*\\1.*\\1.*",
      "^H.*(\\s).*[PYR].[LQY]\\1O$",
      "(?!.*([^E]).*\\1.*)(?=^[EIOUGPW\\s]+$).*E.*E.*U.*",
      "(?=^[ODN ]+$)(N)\\1\\s\\w\\s{2}.*",
      "(?!.*([^T]).*\\1.*)(?=^[ETRY ,]+$).*Y.*",
      "(?!.*\\s.*).*(A).*\\1.*\\1",
    ],
  },
  {
    name: "This one is trivial.",
    code: "d39670aa-8f36-4801-8bf2-1f6d392835ff",
    heng: [
      "G[^H]+H.*",
      "([DN])\\1*\\s+([DN])\\2",
      "⚅\\s[AN]\\s+[AN]\\s⚅",
      ".(\\s+).(\\1.)\\2",
      "⚅\\s+[HL]\\s[HL]\\s+⚅",
      ".+[AG]{2}.+",
      ".+[LN]\\s[LN].+",
      ".+[DH]{2}.+",
      "⚅\\s+[AN]\\s[AN]\\s+⚅",
      "(.(\\s+))\\1.\\2.",
      "⚅\\s[HL]\\s+[HL]\\s⚅",
      "([GL])\\1\\s+([GL])\\2*",
      ".*A.*D",
    ],
    zuoxie: [
      "H[^N]+N.*",
      "([AG])\\1*\\s+([AG])\\2",
      "⚅\\s[GL]\\s+[GL]\\s⚅",
      ".(\\s+).(\\1.)\\2",
      "⚅\\s+[DN]\\s[DN]\\s+⚅",
      ".+[HL]{2}.+",
      ".+[DG]\\s[DG].+",
      ".+[AN]{2}.+",
      "⚅\\s+[GL]\\s[GL]\\s+⚅",
      "(.(\\s+))\\1.\\2.",
      "⚅\\s[DN]\\s+[DN]\\s⚅",
      "([DH])\\1\\s+([DH])\\2*",
      ".*L.*A",
    ],
    youxie: [
      "N[^G]+G.*",
      "([HL])\\1*\\s+([HL])\\2",
      "⚅\\s[DH]\\s+[DH]\\s⚅",
      ".(\\s+).(\\1.)\\2",
      "⚅\\s+[AG]\\s[AG]\\s+⚅",
      ".+[DN]{2}.+",
      ".+[AH]\\s[AH].+",
      ".+[GL]{2}.+",
      "⚅\\s+[DH]\\s[DH]\\s+⚅",
      "(.(\\s+))\\1.\\2.",
      "⚅\\s[AG]\\s+[AG]\\s⚅",
      "([AN])\\1\\s+([AN])\\2*",
      ".*D.*L",
    ],
  },
  {
    name: "Mayan Calendar",
    code: "56beaa3fe8813",
    heng: [
      "(?!.*(.).*\\1)[CS2>O]*",
      "(?!.*(.).*\\1)[EDLR\\s=]*",
      "(?!.*(.).*\\1)[1IOT'\\s-]*",
      "(?!.*(.).*\\1)[EKS0-1'()]*",
      "(?!.*(.).*\\1)[LIFW2();\\s]*",
      "(?!.*(.).*\\1)[INOS1-2'\\s]*",
      "(?!.*(.).*\\1)[DEL2,\\s-]*",
      "(?!.*(.).*\\1)[ADRW,']*",
      "(?!.*([^']).*\\1)[DOW']*",
    ],
    zuoxie: [
      "[^);][^NOS].*",
      "[^0][^IL][^NO].*",
      "[^I].*",
      "[^LR]\\W.*(\\w)\\1[^AW]\\w$",
      ".(.).*\\1.\\w$",
      "(\\w)\\W\\1.{3}\\W\\w",
      "[^S].[^'-][^'(].*[^,]$",
      ".[^R].[^K].*",
      "\\W\\w\\W\\w\\W",
    ],
    youxie: [
      "[^D]\\w\\W\\w[^)]",
      ".[^A].[^N][^I][^KS]",
      "\\W\\w{2}\\d\\w{2}.*",
      "(\\W)\\1(\\w)\\W\\2\\W\\w.*",
      "(\\w)(\\w)\\2\\w\\1\\w\\W\\w.*",
      "\\W[^E](\\W)\\W\\1\\w\\W\\d",
      "(.)\\w\\1\\W\\d\\1.*",
      "\\w{2}\\d[^-]\\w.*",
      "\\W\\d\\w{3}",
    ],
  },
  {
    name: "Word Character Class",
    code: "5ba2fac8-6303-440f-a40a-4c4ba7d12775",
    heng: [
      "(?=(?:(?!(.).*\\1)\\w)+$)(?!(.+2.+))[012]+\\w{2}",
      "(?=(?:(?!(.).*\\1)\\w)+$)[HAT]{2}[^3-6][QI]+",
      "(?=(?:(?!(.).*\\1)\\w)+$)[^A-Z1-4]\\D+[^A-Z124]+",
      "(?=(?:(?!(.).*\\1)\\w)+$)J[^A-Z][LXON]+[^A-Z]",
      "(?=(?:(?!(.).*\\1)\\w)+$)(?!(.+\\d.+))[CARDS]{4}\\w+",
      "(?=(?:(?!(.).*\\1)\\w)+$)[U-Z]+[^A-Z]",
      "(?=(?:(?!(.).*\\1)\\w)+$)[^A-W][K-P]_[^A]",
    ],
    zuoxie: [
      "(?=(?:(?!(.).*\\1)\\w)+$)6?6?6?\\w[8-9][ABC]",
      "(?=(?:(?!(.).*\\1)\\w)+$)[578]\\w+",
      "(?=(?:(?!(.).*\\1)\\w)+$)\\w[123][SNOW]{3}[^G-L]",
      "(?=(?:(?!(.).*\\1)\\w)+$)[^SING]\\D9\\w+",
      "(?=(?:(?!(.).*\\1)\\w)+$)[PECK]\\w[GLADUS]+",
      "(?=(?:(?!(.).*\\1)\\w)+$)[15-9][HOFF]+3?4C",
      "(?=(?:(?!(.).*\\1)\\w)+$)\\w+",
    ],
    youxie: [
      "(?=(?:(?!(.).*\\1)\\w)+$)[^Z\\dXy]\\w+[JC]{2}",
      "(?=(?:(?!(.).*\\1)\\w)+$)[^N-R][VDER]+[42+7]+",
      "(?=(?:(?!(.).*\\1)\\w)+$)[^\\dA-Za-z]\\w+[AFLACK]{3}",
      "(?=(?:(?!(.).*\\1)\\w)+$)[^C-Z\\d]Z[G-X]+[^1-3]",
      "(?=(?:(?!(.).*\\1)\\w)+$)[78]+[NOT]{2}[1-39]{3}",
      "(?=(?:(?!(.).*\\1)\\w)+$)[POE]{2}[^A-Z][O-Z]{2}",
      "(?=(?:(?!(.).*\\1)\\w)+$)[56]{2}[KING]{2}",
    ],
  },
  {
    name: "[Hexagonal] Regex Math",
    code: "92e1bfc7-96fc-482e-8518-8fd11f1d12fc",
    heng: [
      "[1-4]*.[1-4]*",
      "[2-5]*[^-*\\d][^890]*",
      "(.).\\1[-1]+[^1]+",
      "[3-5+^]*",
      "[6-8]\\*([^3-7])\\1",
    ],
    zuoxie: [
      "[0-3]*",
      "[2-9]([1-5])[^+*-]\\1",
      ".*[2468].*",
      "[^0-2]([*+-][^67^])*",
      "(\\W)\\d\\1\\d",
      "[^3-6][3-6][^3-6]",
    ],
    youxie: [
      "[5-9]*",
      "(\\W)\\W\\1[^3+4]",
      ".\\d[^81](.)\\1",
      "[13579][+^*-]+",
      "(.)(.)\\2(?!\\1).",
      "[^2-6]+",
    ],
  },
  {
    name: "Hexagonal Tests",
    code: "fb3efff2-02f0-4d00-a880-c943d872b51b",
    heng: [
      "(?=(?:(?!(.).*\\1)\\w)+$).*",
      "(?=(?:(?!(.).*\\1)[A-F])+$).C+.*FA+.*$",
      "(?=(?:(?!(.).*\\1)[A-F])+$).*",
    ],
    zuoxie: [
      "(?=(?:(?!(.).*\\1)\\w)+$).*",
      "(?=(?:(?!(.).*\\1)\\w)+$).*",
      "(?=(?:(?!(.).*\\1)\\w)+$).*",
      "(?=(?:(?!(.).*\\1)\\w)+$).*",
      "(?=(?:(?!(.).*\\1)\\w)+$).*",
      "(?=(?:(?!(.).*\\1)\\w)+$).*",
    ],
    youxie: [
      "(?=(?:(?!(.).*\\1)[A-F])+$)Z?Q*D\\d*.*(?=.*[AB]$).",
      "(?=(?:(?!(.).*\\1)[A-F])+$)\\d?E+.*(?=.*A$).",
      "(?=(?:(?!(.).*\\1)[A-F])+$)\\s?F[BD](?=.*[B-D]$).",
      "(?=(?:(?!(.).*\\1)[A-F])+$)\\W?A+.*(?=.*[C-E]$).",
      "(?=(?:(?!(.).*\\1)[A-F])+$)[:-?]*B+F.*(?=.*[AD]$).",
      "(?=(?:(?!(.).*\\1)[A-F])+$)[*-?]?(\\[?AE$\\]?)*",
    ],
  },
  {
    name: "Round and round",
    code: "593f19ffb5589",
    heng: [
      "[UPS ]{3,}",
      "(?:[IONIZE] ?)*",
      "[HELLO](.)[PALESTINE]{2}\\1Z",
      "(.)\\1 (.)[IS]{2}\\2",
      "[ACLU]*A[ARE\\s]*",
      "[NIL ']*",
      "[SO]* [SO]*",
    ],
    zuoxie: [
      ".E[^E].",
      ".(?:S | S|SS)(?:I | I|II)",
      "[N-Z](.)\\1[RUNS]*",
      "[^P]\\s[APPLE]*.O",
      "[A-Q](?:NS|SN|NN|SS) (?:AL|LA|AA|LL)",
      ".[ONTARIO]*[UTAH]*",
      "[SIT]*[HI]*[SIT]*",
    ],
    youxie: [
      "(?:OL|SN|UT)*",
      "[SALT]* [EARTH]*",
      "(\\d|\\s)(?:AN|NA)\\1(.)\\2",
      "(.)[RAIL]*\\1O\\1",
      "['?!\\.] (?:PIN|PNI|IPN|INP|NIP|NPI)\\W",
      "[E N T E R P R I S E]*",
      "[LEFT](.)\\1[UP]",
    ],
  },
  {
    name: "Hex Recursion",
    code: "56bc4e4991f83",
    heng: [
      "([^.])\\1+(\\S)\\2",
      "([^.])\\1+(\\S)\\2\\W",
      "([^.])\\1+\\w{2}\\W\\1+",
      "([^.])\\1+(\\S)\\2\\w\\1+",
      "([^.])\\1+(\\S)\\2\\S\\1+",
      "(?!^(.)\\1.*)(\\S)(\\S)\\w\\2\\W([^.])\\4\\W\\4+",
      "(?!^(.)\\1.*)(\\S)(\\S)\\w\\2\\W([^.])\\4+",
      "(?!^(.)\\1.*)(\\S)(\\S)\\W\\2\\W([^.*])\\4\\3\\4+",
      "([^.])\\1+(\\S)\\2\\S\\1+",
      "([^.])\\1+(\\S)\\2\\w\\1+",
      "([^.])\\1+\\w{2}[^\\s*]\\1+",
      "([^.])\\1+\\S{3}",
      "([^.])\\1+(\\S)\\2",
    ],
    zuoxie: [
      "[.\\s^]+",
      "[.*\\s]+",
      ".{5}([\\sE])\\1.*",
      ".{7}[\\sG].*",
      "\\s.*",
      "(\\S)(\\S)\\w\\1\\W{3}\\2\\W+",
      "(?!^(.)\\1.*)(\\S)(\\S)\\w\\2\\3\\W+",
      "(\\S)(\\S)\\w\\1\\2\\W{2}\\2\\W+",
      ".{5}(.)\\1.*",
      ".{7}[^*E\\s].*",
      ".{5}[^EB].*",
      ".*(.)\\1.$",
      "(.)\\1{4}[\\s.]+",
    ],
    youxie: [
      "[.\\s]+",
      "[.*\\s]+",
      "[!*E\\s]+",
      ".{7}[BER\\s!].*",
      ".{5}([AB*])\\1.*",
      "(?!^(.)\\1.*)([^\\s*])(\\S)\\w\\2\\3\\W{2}\\W+",
      "(?!^(.)\\1.*).*",
      "(?!^(.)\\1.*)[^\\s.](\\S)\\w\\2\\W{2}\\W+",
      ".{5}(.)\\1.*",
      ".{7}[!\\sG].*",
      ".{5}[!\\sX][!\\sP].*",
      "[.*\\s]+",
      "[.\\s]+",
    ],
  },
  {
    name: "X-Y-Z Hextreme",
    code: "5d7b3d7b08b00",
    heng: [
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){5})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){6})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){7})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){8})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){9})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){10})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){11})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){10})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){9})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){8})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){7})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){6})[XYZ ]*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){5})[XYZ ]*",
    ],
    zuoxie: [
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){5}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){6}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){7}).*Y..X.*Z.*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){8}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){9}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){10}).*Z(.+)\\w\\3\\w.*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){11}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){10}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){9}).*X..\\s.*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){8}).*Z.{2,}X.*Y.*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){7}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){6}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){5}).*Z..Y.*",
    ],
    youxie: [
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){5}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){6}).*ZX.*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){7}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){8}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){9})^\\s*Y.*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){10}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){11}).*\\w..Y..\\w.*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){10}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){9}).*Z\\s*$",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){8}).*Y.+X.+Z.*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){7}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){6}).*",
      "(?!.*([^\\s]).*\\1)(?!(.*\\s){5}).*X\\s*$",
    ],
  },
  {
    name: "British Rock",
    code: "5698bb30a84c3",
    heng: [
      ".[DJHT][MIDDLE][S-T][AEIOU]",
      "(?=\\W\\w+).[SIX][{-}N-Z][AK]{2}.",
      ".*[ACL]E\\x44\\s\\w{2}",
      "(?=.P.*).*P.*P.*P",
      ".[A-N][SPOK]\\W(FRED|FRODDO|FLOYD)",
      "\\W(MOTORHEAD|JUDAS?)\\W\\x50",
      "(?=.*S.*).*E.*",
      "(POD|RON|TET)\\W.[BAN]",
      "(?=\\w+).*D[DE][^A-M-O-Za-z_0-9]\\W",
    ],
    zuoxie: [
      "D.[AI]{2}[$#.]",
      "[\\w\\W]{2}(\\s){2}[\\w\\W]+",
      ".([^\\S]).*(\\1)(.)$",
      "(?=\\w+)(?:^E)[^A-Ya-z\\d_](N).*\\1.",
      "(?=.*I.*I$)[^A-DF-Z].*",
      "(?=.*L.*I.*).*",
      "I(?:[A-N])(.)\\1K.*",
      "[SLH]{3}[NP]{2}[A-T\\s]",
      "(?:.)(.)\\1PI.*",
    ],
    youxie: [
      "(?:.)(.)(\\1)\\W\\w",
      "(?!.*E.*).+",
      "(?=.*E.*E.*).*",
      "\\w\\x20[^E]\\w*\\x20\\w{2}\\x20",
      "^[--/]\\x4DT.*\\x57$",
      ".+",
      "[I-J].*[JAC].",
      ".*([\\x4B])[T-Z]",
      ".{2}(.)\\1\\1.*",
    ],
  },
  {
    name: "U Make Me Feel So Good",
    code: "5b36333fcf11b",
    heng: [
      "[RAIL]+",
      "(?=.*I.*T.*)[WRIT]+\\s",
      "(?=.*A.*Y.*T)[PASTEY]+",
      "[SPACE]{2}[DANCE]Y\\sR",
      "(?=.*S{2})[ESSENSE]+I",
      "((NX)|(EU)|(OB)){2}",
      "[REEFER]*",
    ],
    zuoxie: [
      "[BIER]+",
      "[STOFFF ]+",
      "\\s(.)\\1[RUSH]+",
      "[TNET LSD]+",
      "[A PARTEY!]+",
      "[TRIPS]+",
    ],
    youxie: [
      "[CRIMINAL][JUSTICE]+[ACTS]",
      "(?=.*[NXP]PP.*).*(.)\\1",
      "(?=.*DA.*)E[DOSE]+.*",
      ".(.)Y\\1(.)\\2",
      "[YITA ]+",
      "[COURT]* [TRAIL]",
    ],
  },
  {
    name: "Star Wars",
    code: "5688f397e5d6c",
    heng: [
      "[A-G](.)[L-Z](\\1)",
      '(?=.*U.*)[^"BARG"]+',
      "[TIME|SR]+",
      "(TE|EP|TH|A)+",
      "(WE|O)+[FOR]+",
      "(FO|E|TH)+",
      "R?[A-E]{2}\\W",
    ],
    zuoxie: [
      ".*\\!",
      "[MZ](E)[OF]+\\1",
      "\\w[ACID]\\w+",
      "\\w[DTG]{2}\\w+",
      "(.)(\\1)(WT|SE)+",
      "[AEIOUT]+",
      '[RTD]+["BA"]+',
    ],
    youxie: [
      "[^BEFW]+",
      "C\\w{3}[^T]",
      "(.)(\\1)+[^D]",
      "\\W[EFG][RUST]+\\w",
      "(.)(\\1)[^E]+(\\1)",
      "[A-I]{4}N",
      "(E|PM)+O",
    ],
  },
  {
    name: "Shapes",
    code: "5699d21c55c41",
    heng: [
      "(?!^..\\\\)(?!^.\\.)\\\\([\\s.])([\\\\.])\\2{2}\\1\\/.*",
      ".+",
      ".+",
      "(.)\\1.*",
      "(.)\\1{2}\\W{5}\\1{3}.*",
      "(.)\\1{4}..\\1{5}.*",
      "(.)\\1{5}\\W\\1{6}.*",
      "(.)\\1{4}..\\1{5}.*",
      "(.)\\1{2}\\W{5}\\1{3}.*",
      "(.)\\1.*",
      ".+",
      ".+",
      ".+",
    ],
    zuoxie: [
      "-.*",
      ".+",
      "(\\.).{3}\\1.{3}\\1",
      "(.)\\1.*",
      "(.)\\1{2}\\W{5}\\1{3}.*",
      "(.)\\1{4}..\\1{5}.*",
      "(?=^.{6}\\|)^(.)\\1{5}\\W\\1{6}.*",
      "(.)\\1{4}..\\1{5}.*",
      "(.)\\1{2}\\W{5}\\1{3}.*",
      ".{2}(.).\\1.*",
      ".+",
      ".+",
      ".*",
    ],
    youxie: [
      ".*",
      ".+",
      ".+",
      "(.)\\1.*",
      "(.)\\1{2}\\W{5}\\1{3}.*",
      "(.)\\1{4}..\\1{5}.*",
      "(?=^.{6}\\|)^(.)\\1{5}\\W\\1{6}.*",
      "(.)\\1{4}..\\1{5}.*",
      "(.)\\1{2}\\W{5}\\1{3}.*",
      "(.)\\1.*",
      ".+",
      ".+",
      ".+",
    ],
  },
  {
    name: "Shift Cryptosecurity",
    code: "5aa645653afc2",
    heng: [
      "I*.*NI.*[SL]",
      ".{3}[THI]I",
      "A*B.{4}X*",
      "Z*X.*",
      ".*[G].*Y.*",
      "K+.*[G].*",
      ".*T+YA.*",
      ".*C[^YTA]*.{1}",
      ".*",
    ],
    zuoxie: [
      ".D.T.",
      "F.{2}(EQ|RT).*",
      ".I.B.K.",
      ".HJ.O.(BY|AZ).*",
      ".[TYL]RP...C",
      ".*Q.F.T.+B",
      ".PU.V.",
      "[NIL]...Q",
    ],
    youxie: [
      ".*",
      ".*N.*V{2}.*",
      "I*S.*IB",
      ".*Z.*V.*X.*V",
      ".*[GL]*.*",
      ".*L.*K.*N.*G.",
      ".*[YI].*",
      "O.*S+",
    ],
  },
  {
    name: "Regexide Geocache",
    code: "5a7ed792493c1",
    heng: [
      ".?(FN|SN|EF|VN|VS|FS|NE)+",
      "([BISON])[A-E](\\W)\\d\\2",
      "[TREES]{4}[5-9]*[2-4]*",
      "[A-E]{2,3}[F-S]+\\d+",
      "([FUN]+)([D-F])\\2(1|2|4|9)\\3",
      "[FIVE]+(?=[^2-4]{2})[1-5]+",
      "(T?W?I?NK?Y?)+",
    ],
    zuoxie: [
      "[0-1]?[1-2]?[2-3]?[3-4]?[4-5]?[5-6]?.",
      "[4-6]{2,3}[0-2]+[NEW]+",
      "[\\.\\-\\\\\\,][^3-7](?!.*(.).*\\1)[FERN]*",
      "((.)(3))((\\2)(.))((.)([MICRO]))(\\9)",
      "[FEVERS][\\*\\+\\.\\=][A-F]{2,5}",
      "[GC7ANTE]*",
      "(?!..[A-F].)[EFFORT]*",
    ],
    youxie: [
      "[WINNER]+",
      "[REFINERY]+",
      "([WET]F)+[TWO]{2}",
      "(N\\d?E){2}[^B-E]*",
      "[^2-4]{2}.*",
      "[^46-9]+[VISA]+",
      "[^1][^0-3].*",
    ],
  },
  {
    name: "Random Stuff",
    code: "5b7f363515f89",
    heng: [
      "(?=\\W\\d)(.).\\1",
      "(?!.*(.).*\\1.*).[[-_]*.",
      "(?=\\w\\W.*)(?!.*(.).*\\1)[\\040\\042\\043\\x42\\052]*",
      "^/.+\\D",
      "(?!.*(.).*\\1.*)[A-Z]*",
    ],
    zuoxie: [
      ".*\\x4b.*",
      ".*\\x4d",
      "(?=(^\\S{2}\\s.*))(?=(.*\\s\\S{2}$)).+",
      ".\\W*",
      "(?!.*(.).*\\1.*)[\\102^\\x25]*",
    ],
    youxie: [
      ".*\\x52.+",
      '(?=.(.)\\1.).*"+.*',
      "(?!.*(.).*\\1.*).'.[^\\[].",
      "(?!.*(.).*\\1.*)(\\x34|\\120|[*\\]])*",
      "(?!.*(.).*\\1.*)[\\x23-\\045]*",
    ],
  },
  {
    name: "Song Quote Bonus - Happy New Year",
    code: "5e0a2ab40a18b",
    heng: [
      "(?=.* ).[YAY ]+[W\\W]+",
      "(?=.*(.)\\1)[A-M ]+",
      "(?!.*(.)\\1)[HE GAVE]+",
      "(?!.*IE)V[NOISE]+\\W+",
      ".\\.[\\sOFA]*[^LATE]",
      "[LORD]+ W.(.)[^DIE]\\1",
      "([YES NO]|V.R)+",
      "(?!.?S).[^A FIEND]+.",
      "[A FISH][A FiSH]+.",
      "[KINDNES]+\\s.",
      ".(.)(.)\\2\\1",
    ],
    zuoxie: [
      "([AEIOU])\\1 .-.",
      "\\w[FRIEND]+ .",
      "[DUST\\WEB]+",
      "(\\W*A[^Q-T]*){3}",
      "[^A][A][BROWN IE]*",
      "(?!(.*\\W){3})[^G-JQ-V]*[HEIST]*",
      "[^B-K]+E(.)[D-X]{4}\\1",
      "[^G-IW\\W]* [^S\\s]*",
      "[FRIDA .]+",
      "(?!.*[GRAIN])M.[^\\WE].+",
    ],
    youxie: [
      "(.)(.)\\2+\\1[N-Z]",
      "(?!.*D)[^H-RT-Y]+.\\.",
      "[^\\sC-L]+[A\\sH]+(.)L.\\1",
      "(?!.*[L-Z])[^\\WE]+[\\WE]. .+",
      "A( O?[ARISE]*){3}",
      "(?!.*[IFU]\\W)[F-J-U-Z ]+ M",
      "(.)\\1(.)H\\2(?=[AEIOU]+$)..(.)\\3",
      ".([^E]).(\\w)\\1(?!.*\\2).*",
      "[REAL ITY]+",
      "[WALL.E]*(.)\\1.",
    ],
  },
  {
    name: "solution middle row (char 2, 4 and 7 lowercase)",
    code: "591d9cd23f7ef",
    heng: [
      "(S5|Q3)(PG|HW)",
      "(FXY|TFZ)(0|1)(U|X)",
      "(A|U)(AW|VC)(FZ|O9)\\1",
      "[A-Z0-9]*",
      "(ZPP|ARD)(WU|RE)(E|T|X)",
      "(17|31)(PA8|AS5)",
      "(MM|FF)[1-5](T|Z)",
    ],
    zuoxie: [
      "(VE|HT|HX|VX)(5Z|0T)",
      "(A|U)(QU|ME)(AU|S4)",
      "(U9|XZ)(5W|0R)(A|V)(M|F)",
      ".0.*",
      "(PY|HZ)(CC|WZ)(R|P)(3|1)",
      "(3X|5F)(VMA|AFZ)",
      "(ST|QF)(A|U)(7|5)",
    ],
    youxie: [
      "(M1|F3)(A7|Z5)",
      "(M|F)(7|1)(R|P)\\1(A|U)",
      "(UP|4A)(DCV|PZA)(F|T)",
      "(Z|T)(ARD|SWU)(CF|AX)(Q|S)",
      "(0|5)(U|E)\\1(OY|FZ)\\1",
      "T.*",
      "(VUUG|HAXW)",
    ],
  },
  {
    name: "Avatar",
    code: "57c4583abc27d",
    heng: [
      "(?!(.)\\1)[SOKKA ]+",
      "(?!.*([^(Θ ⌅ Θ)^ ∫ᐠ]).*\\1)(?=\\B.\\b).*(.).*\\2.*",
      "[APPA OR MOMO]+",
    ],
    zuoxie: [
      "(?!(.)\\1)[TY LEE OR MAI]+",
      "(?!.*([^R]).*\\1)[IROH ]+",
      "(?!(.)\\1)[SUKI ]+",
    ],
    youxie: [
      "(?!(.)\\1)[^AZULA][^OZAI]",
      "(?!.*(.).*\\1)[KATARA ]+",
      "(?!(.)\\1)[ZUKO OR TOPH]+",
    ],
  },
  {
    name:
      "(?:[C-Z]|[0-9])+([F-P][A-I])(?:[E-V]){1,5}([^E-V]){1}(\\2)*(?:[^A-D]|[^E-Z])([^L-S])+(?:[L-R]|[^A-E])*(\\1)?([0-9]+|[^A-F])+",
    code: "592f7eec3cdea",
    heng: [
      ".[AMERICA]",
      "[INTERNET][^A-E][PROTOCOL]",
      "[LIONS][TIGERS][BOARS][NEWTS]",
      "(F|AK|EN|E|WS)?[^RECEDE]{3}",
      "(\\S)?(SN|EK|BE|LO)+(\\S)?",
      "[FREEDOM][RINGS].",
      "[^A-P]+",
    ],
    zuoxie: [
      "[WORK]+[USA]+",
      "[NORTH]+.[EDGY]+",
      "[POINT][OF][VIEW].[^O]",
      "[^NOTE][FINE]+",
      "(ZI|P|L|IN)+E",
    ],
    youxie: [
      "[N-Z]+(.)\\1",
      "[^T-Z]+[A-M]",
      "(UL|TI|MA|TE)V([F-J])\\2",
      "(O)\\1+[A-G]+[^A-Q]?",
      "(W|I|N)+\\1?[PIMP][COVFEFE]",
    ],
  },
  {
    name: "Spycursion Challenge @ PAX West",
    code: "5b682343c4231",
    heng: [
      ".(.)\\1{2}R",
      "(OL|PS|TI)+",
      ".*",
      "T[C-E]{2}[I-N]+",
      "(.)\\1C[LEAR]+",
    ],
    zuoxie: [
      "[HACK].*",
      "I?[^ACPI][^API]*[RUN]{2,}",
      "[P-R]{1,3}[ID][CLOJURE]+",
      "[RATE].(DC|RD|NE)[PEAR]",
      "[^BUILD]+",
      ".*(.)\\1.+",
      ".(PC|OR|TM)",
    ],
    youxie: [
      "[^A-CX-Z]+",
      "[^READ]+",
      "(.)[BYTE][BIT]+\\1",
      "(DC|RJ|EZ).*",
      "[QUINE]+[^RISK].",
      "[ACPI]+",
      "[RISK]+",
    ],
  },
  {
    name: "Scala Traits I Like",
    code: "5a976d162e5d6",
    heng: [
      "[FOR][BETTER][JAVA][CODE]+[TOO]",
      "[PARTIAL]?[AN][D ]+[IMPLICIT]*F[UN]{2}[CTIONS]*-",
      "(ALL?|THAT|\\W[HEN]?|[COMPARED])+T(O)\\2[C]\\2",
      "[AND ]+NO[POIN]*[TER]{2}S?",
      "[EXPRESSION ORIENTED]+",
    ],
    zuoxie: [
      "[OPERATOR][R][ICH]",
      ".[GENERIC]+[TYPES]+",
      "[FUNCT]{2}[IO]*N[LITERALS]*",
      "[C][URRY OF ARG LIS]*[TS]+",
      "[NESTED]*[DEFINITIONS]+",
      "[JVM]\\s{2}[BASED]+",
      "[BO][UND][VARIAB]?[LES ]{2}",
      "[CO][MPAN]{2,}[ION OBJECT]?",
    ],
    youxie: [
      "(SUPPORTS|BIG)*[D]?[ATA ]+",
      "[OBJ]?[E][CT]?[LAZY]+I?[N]+[STANTIATION]*",
      "[DON'T ]{4}[REPEAT]*[YOURSELF]",
      "[SINGLE]?[TON]+[ ][OBJECTS]+",
      "[TYP]*[E][I][NFERENCE MOJO]+",
      "[IMMUTABILITY]{2}[I-S]+[BEAUTY]+",
      "[FOR][COMPREHENSION]+",
      "[-TYPE CONSTRAIN]+\\W[TS]",
    ],
  },
  {
    name: "Can you pattern match?",
    code: "5688bcd879f21",
    heng: [
      "(.)(\\1)(\\2)(\\3)",
      "(.)(.)(\\2)(\\3)(\\1)",
      "(.)(.)(.)(\\3)(.)(\\1)",
      "(.)(.)(\\1)(.)(\\3)(\\2)(\\5)",
      "(.)(.)(.)(\\3)(.)(\\1)",
      "(.)(.)(\\2)(\\3)(\\1)",
      "(.)(\\1)(\\2)(\\3)",
    ],
    zuoxie: [
      "(.)(\\1)(\\2)(\\3)",
      "(.)\\|\\/\\W(\\1)",
      "(.)\\\\(\\1)(.)(\\3)(\\2)",
      "(.)\\W{5}(\\1)",
      "(.)(.)(\\2)(\\1)\\\\(\\4)",
      "(.)-\\/\\W(\\1)",
      "(\\s)(\\1)(\\2)(\\3)",
    ],
    youxie: [
      "(.)(\\1)(\\2)(\\3)",
      "(.)(.)(.)(.)(\\1)",
      "(.)(.)(\\2)(\\1)(.)(\\4)",
      "(.)(.)(\\2)(\\3)(\\4)(\\5)(\\1)",
      "(.)(.)(\\1)(.)(\\4)(\\3)",
      "(.)(.)(.)(.)(\\1)",
      "(.)(\\1)(\\2)(\\3)",
    ],
  },
  {
    name: "Royal Game",
    code: "58950c6b6f341",
    heng: [
      "[R3AL]+[ACES]+",
      "\\.*[SOLVE]?[THINGS]+[VERY\\s]*[QUICKLY]",
      "(I|DID|IT|O|N){1,3}(M|Y)+[0WN]?",
    ],
    zuoxie: [
      "1?([LOVE])+[PLAYING]*[THIS]?",
      "A?L?I?E?N?\\s(M|A|RI|N|ES)+",
      "[R3A11Y]+[LONG]?[AGO]?",
      "([0-4])+[YEARS]?(O|F)*[AGE]?",
    ],
    youxie: [
      "\\??(G|O)*(O|G)?(\\s\\?)?",
      "(G|I|F)*[M0R3]*",
      "[YOU]+(A|R|E|\\s)?[NOT]*[ALONE]{1,2}",
      "[LAS3RTAG\\!]{2}",
    ],
  },
  {
    name: "CSGO",
    code: "597c3b7898ebb",
    heng: [
      "\\.?[J-T]?(H|O)?",
      "([Q-Z]|\\W?)+",
      "(\\W|N|B)+",
      "[WHY](.)(\\1)",
      "[HIGUYZ]?[OREO]?",
    ],
    zuoxie: [
      "(\\s)?(H|B)?[EURO]{2}",
      "[^P-R]?[NOPROBS][F-JS-V]{2}",
      "(H\\W|HT){1,3}[NOW]+",
      "\\.?[ROY\\s]{3}",
    ],
    youxie: [
      "[HOW]+[^HEYOR]\\W?",
      "[^BRIE\\s]+",
      "(U|B\\s|R\\s|R|B)+\\.?",
      "(\\s)?(A|C)?[SHO]{2}",
    ],
  },
  {
    name: "Childish way of talking!",
    code: "59d0c71ecef9a",
    heng: [
      "[MUNCH]\\W",
      "[DOPPLER]?[EEENNNOOOAAAA!]*",
      "[CLICK].[HOWLER]+",
      "[FLOAT]*",
      "[CLIP]*[CLOP]?[CLIP]?[CLOP]*",
    ],
    zuoxie: ["[TEE\\sssH!]*[POP]*", "(.)(.)\\1\\2", "(\\W)(.)\\1\\2", "[H-O]+"],
    youxie: [
      "[^KLACK]*",
      "[SPLASH]*.\\W[NASH]",
      "[4CHN]?[TICK]+[MOOO]*",
      "[REEEEE]['SCREAM']*",
    ],
  },
  {
    name: "Employee mandatory 2019",
    code: "59d8b2dd86bd0",
    heng: [
      "[VOICE]{1,3}(?=G|H).T[#-.]",
      "[KILL](PSI|NEX|AMP|RET|US6)(.)\\2[ BABYSPIDERS]",
      "^(?![KILLING\\sJAR]*$)(.)(.)(.)\\1\\3[,-/]",
    ],
    zuoxie: [
      "[EMPATHY]?.*",
      "[6\\-HOURS]?[~]?[FX][R-Z]",
      "(.)[ARTIFICIAL\\.DNA]\\1",
      "[PPGS]+",
      "[MILGRAM]+[KILEJ]",
      "[OUTERSPACE]+",
      "^V(?![INTERGALACTICWAR]*$).*",
    ],
    youxie: [
      "(WA|SP|ARM)?(TK|♤♡|JK)",
      "[ROSEN][PAVLOV]+",
      "[MERCERISM]+[MOODORGAN]+",
      "[^PENFIELD][EXISTENTALDISPEAR].*",
      "[SF]+[BOILED\\.DOG].*",
      "[IRAN]?\\.[FORTE]{2}",
      "(\\W)+[^LETMETELLYOUABOUTMYMOTHER]*",
    ],
  },
  {
    name: "Area-51",
    code: "5d8a579f3d314",
    heng: [
      "(AND|BUT|THE)",
      "[MULDER.]+",
      "[HURT]+",
      "\\s+\\S+S\\s+",
      "\\.([\\s.]+)\\1",
      "[.]+(IN|OUT)[.]+",
      "[THE]+[AREA51]+",
      "([.\\s])([.\\s])\\2\\1",
      "[SCULLY.]+",
    ],
    zuoxie: [
      "[X.FILES]+",
      "\\W+\\.R\\W+",
      "H\\s+[TV][EZ]\\W+",
      "\\W[TSA]+\\.[UHHH]+\\.",
      "[ET]\\W[UFO]I\\s[OTHER]{2}",
      "[HERO.]{3}(\\W)\\1.",
      "T(.)T.\\1",
    ],
    youxie: [
      "([.]+)T\\1",
      "\\.+\\s+\\w{2}\\W+",
      "\\W+\\w+\\W+\\w",
      "\\.(.)T\\..\\1\\.",
      "[EEK]\\W+[SAVE][US]\\..",
      "\\W+\\w\\W\\w",
      "[^\\s]+\\s+\\w\\W\\w",
    ],
  },
  {
    name: "Lost",
    code: "5d66cc8555819",
    heng: [
      "[HR](H|RRH)+(HG|RE)",
      "(.(.))\\1.*\\2",
      ".*",
      "[^H]*(.)H[^H]*\\1",
      "([^BR]|BR)+",
    ],
    zuoxie: [
      "([EC].|[RA])+",
      "[^B]*B[^B]*",
      "[^RS]*AS.*",
      "([^R]|HR)+",
      ".*(.)\\1.*",
      "[^GE]*[RE]*",
      "(.).*\\1",
      "(RAW|.E).?",
    ],
    youxie: [
      ".*(GR|EC|RT).*",
      "[^HE]*H[^H]*",
      "R+[^R]*",
      "H*\\s[^\\sB]*",
      "[QB](SG|BH|BR)*",
      "[RA](DA|CH|XU)+",
      "(\\s|ST|M[RQ]H)*",
      "([RE].G|[CA].E)",
    ],
  },
  {
    name: "Shirt concept",
    code: "5666ec760d6dc",
    heng: [
      "ME|YOU?|US",
      "[SAVANT]{3}",
      "[P-R-]+[AEIOU]*",
      "[TOO]*[SMART]",
      ".*",
    ],
    zuoxie: ["[EXTRA]*", "(UH)?(UM)?(AR)?(OI)?", "(.|[TEST])+", "[^A-LO-Z]*-?"],
    youxie: ["(IM|NO|TW|IT)-", "A*[M-P]+", "[PRIMES]+", "(.).\\1"],
  },
  {
    name: "Audrey!!",
    code: "5645f36e70634",
    heng: [
      "[Everyone<Audrey!!][^4-9]",
      "(SI|TU|\\s(AVA)*I\\s)?(C0MME|JE|T'AIME!)?",
      "[LORSQUE]+[JE(TE)VOIS]*",
      "(MONCOEUR)?(\\s)['YMMOBI(LISE)]\\2",
      "[TUES]*T?(OU)*[CEDONTJ'AI]*((BE|SO|IN)!*)?",
    ],
    zuoxie: [
      "(TU|[EST])\\s(U[PER(BE)]*)",
      "[\\sVY]+(O|0)",
      "[I3-5O\\s]+",
      "(\\s|\\W)?\\s+L",
    ],
    youxie: [
      "I?[\\sLO]+(VE)*(YOURSMELL)?",
      "[^AndEverythIngelseAbout]*[YOU\\s!]+",
      "(<|\\s)[VI]+[^\\1!]",
      "[^TS]\\s\\d",
    ],
  },
  {
    name: "Triple fun",
    code: "5ad90c4637631",
    heng: ["[^1]*", "[02]+[01]+", "([01])\\1([01])\\2", "[^1]+", "[12]*"],
    zuoxie: [
      "(?!.*(.).*\\1)[0-2]*",
      "[12]+(.)\\1[12]+",
      "(?=(.)(.)\\2\\1)[12]+",
      "(.)\\1[12]",
    ],
    youxie: ["(.)\\1[0-2]*", "(..)\\1", "[012]+[01]+", "(?!.*(.).*\\1)[012]*"],
  },
  {
    name: "Ignis-Terra-Aer-Aqua",
    code: "5bdf575a66ee3",
    heng: [
      "[☺-♡]+",
      "[ZOSIMOS]\\w*[^TERRA]",
      "([MERCURY])[^\\w ♀-♄]*\\1",
      "([AER]\\W|\\W[AQUA])*",
      "[⊖IGNIS⊖]*",
    ],
    zuoxie: [
      "(?!.*(.).*\\1)[^SILVER]*",
      "(?=(.*[⊖\\u2644]){2})[SALT][^☽☾MAGNESIUM]*",
      ".*\\u2643.*",
      "[^☾-☿][COPPER \\u26A5]*.",
      "[^♁-♃]+",
    ],
    youxie: [
      "[AMALGAM]+.",
      "[\\W GOLD]*",
      "(?!.*(.).*\\1)[☉PLATINUM☉\\u2640-\\u2644]*",
      "(?=.*(.).*\\1)[SULFUR\\u263D-\\u263F]*",
      "[BISMUTH\\u2642]+",
    ],
  },
  {
    name: "Beehive",
    code: "a18b773e-35d2-4a90-bfd5-f1ab0de19050",
    heng: [
      "(.)\\1\\1\\.",
      "([OH]\\s)+[NO?]?",
      "[EY][E\\s]+[CY]{2}",
      "([OM]\\s)+[BO?]?",
      "(.)\\1\\1\\.",
    ],
    zuoxie: [".*", ".*", ".*", ".*", ".*", ".*"],
    youxie: [
      "[E\\s\\sO]{3}",
      "(\\s\\s|\\sH)+",
      "\\s+M\\s+",
      "[\\sO.]+[WHAT]?",
      "[BYE ]+",
      "[CNNNN.]+",
    ],
  },
  {
    name: "Like a VGA plug",
    code: "5a26c2c21538d",
    heng: [
      "[PC/XT PC/AT]",
      "[256K]?[RAM]+",
      "[OP]{1,2}[CIRCUS]",
      "[DZUB]+",
      "[;-G]",
    ],
    zuoxie: [".*", "[ANALOG].*", "[ATI]*[RASTA][PALLETTE]"],
    youxie: ["(?=E.*P.*).*[XGAV-[].", "[OR\\-D]+", "[D-P][:-C][S-U]+"],
  },
  {
    name: "electrical measurement of water purity",
    code: "5b08166db7d25",
    heng: [
      "[\\u2127]?([M-P])[A-K]\\1",
      "[1/OHMSR]*(.)\\1",
      "[RC][TIMe]*(.)\\1",
      "[M-O][P-U][P-U]+[H-L]+",
      "[TotalDissolvedSolids]+",
    ],
    zuoxie: [
      "(?!=(.*(.*)\\1)).*",
      "[TOES]+",
      "(.)[N-P]\\1..",
      "(.)[O-S]\\1N",
      "[CSM]+",
    ],
    youxie: [
      "[A-E][NC]*",
      "([R-U])\\1[D-L]\\1",
      "\\x53\\x54(.)\\x52\\1",
      "[F-H]+[IOE]{3}",
      "[ELECTRIC][OHM]+",
    ],
  },
  {
    name: "Best Piano piece ever!",
    code: "5dc1ad4402953",
    heng: [
      "(?!.*(.).*\\1)E[LEVEL]+",
      "(?!.*(.).*\\1)[RI]+[MOZART]+",
      "(?!.*([^A]).*\\1)(?=^(.)[D-Z]+\\2$)[DAGDAI]+",
      "(?!.*(.).*\\1)[PNC\\.]+",
      "(?!.*(.).*\\1)[1 2]+",
    ],
    zuoxie: [
      "(?!.*(.).*\\1)[A-Z]+[\\.-1]",
      "(?!.*(.).*\\1)[A-Z]+\\d",
      "(?!.*(.).*\\1)[A-Z][A-K]+\\W+",
      "(?!.*(.).*\\1).*",
      "(?!.*(.).*\\1).*",
    ],
    youxie: [
      "(?!.*(.).*\\1).*",
      "(?!.*(.).*\\1).*",
      "(?!.*(.).*\\1)[RIPP1E]+",
      "(?!.*(.).*\\1)[LARGO_C]+",
      "(?!.*(.).*\\1)[VELMA]+",
    ],
  },
  {
    name: "Make mine a '99",
    code: "5daf22b3dfa3c",
    heng: [
      "(?!.*(.).*\\1)^[\\--0][/ROAM\\\\]*",
      "(THE)?(LANd)?[^MILLION POuND cash BuRNt]*",
      "(?=[^\\.\\-].*JU.*)\\W[JUJUSUMU]+",
      "(?=.*(F.*)E)T(.).(\\2)..",
      "(?=\\w\\W\\w+)(?=.*AN.*)(?=[DANCE\\.]+)[^ILLUMInaTI].*",
      "[IC]+E[^CREAM]*[^VAN]",
      "(?!.*(.)\\1)\\w\\W*",
    ],
    zuoxie: [
      "(?=.*C.*\\W)[C\\\\UT]+",
      "..(.)\\1.",
      ".(.).*\\1",
      "(?=.*E.*\\.)[^SCOTLAND]+",
      "(?=\\W.*H.*I)[^TWENTY ThREE]*",
      "(..)\\1",
    ],
    youxie: [
      "[SZI]+[DTX]+",
      "(?!.*([^\\.])\\1)\\.[I\\.E/]*",
      "(?!.*(.)\\1).[K-P]A.*",
      "(?!.*(.)\\1)T.*\\W",
      "(?=.*S.*)(.)(.)(.)(\\2).*",
      "(?=[U-Z]+)(..)\\1",
    ],
  },
  {
    name: "Gotta try'em all!",
    code: "2df29966-eab5-4fbf-9176-b8fd6036fcc2",
    heng: [
      "[LEDIAN]+",
      "[JIGGLYPUFF]+",
      "[LUXRAY ]+",
      "[DUSKNOIR]+",
      "[AZELF]+",
    ],
    zuoxie: ["[XERNEAS]+", "[TABUNNE ]+", "[GROTLE]+", "[GOLEM ]+", "[AZELF]+"],
    youxie: [
      "[FEAROW]+",
      "[FURRET ]+",
      "[DRAGONAIR]+",
      "[DEWGONG ]+",
      "[VULPIX]+",
    ],
  },
  {
    name: "Kings Viking 2019",
    code: "5c2a31fe4fa25",
    heng: [
      "[HIJACKING]*P",
      "[PWN][CRYPTO][STEGANOGRAPHY][REVERSING][WEB]",
      "[VULNERABILITY]*[ATTACK][INJECTION]",
      "[SESSION][PRIVILEGE][XSS]V[FIXATION]",
      "[HACKING]+",
    ],
    zuoxie: [
      "[AKAGI]+",
      "W[VALKYRIA]+[LAUGHINGCAT]",
      "P[KOREEDA]+[SAKAI]+",
      "[KANZAKI]+[NIWA]+[KINUGASA]+",
      "[SHUUHEI][RYOU][YUSUKE][NISHI]",
      "[KATOU]PY",
    ],
    youxie: [
      "[OOK][UNLAMBDA][TYPESCRIPT]",
      "[LISP][GO][ECMASCRIPT][PHP]",
      "[.NET][RUST][SCALA][DYLAN][APL]",
      "[GROOVY][JAVA][R][ICON][HSP]",
      "[IO][KOTLIN][EIFFEL][DART]",
      "[^OCAML]+",
    ],
  },
  {
    name: "DurHack-2018-p1",
    code: "5bf03d21903fa",
    heng: [
      "(I|OR|POLLY)?(WANNA|CRA|CKER)?",
      "C[AK]E?[AD][ORE]!?",
      "(SOME)?.(LAR|GE)( HE|XES)",
      "(OR|AND|XOR|NOT)A*L*I*E*N*",
      "(PUR|GE)(TI|RED)(PEA|SA|NT)",
      "[Q-W][-ER][TY]?(MA|SH)I!*",
      "(I|AM|SMA|RT!)(\\\\//\\\\|\\?|//\\\\){1}",
    ],
    zuoxie: [
      "I[A]+I(\\?|\\!)",
      "(C|S)+L(A)*SH\\!",
      "(DEV|REL)+(IS)?I*T?",
      "AD+(E?V?)XAT\\-[R]+[EST]?",
      "RE+DA?ET",
      "(HA|CK)G[A]*NG",
      "ICE[CREAM]",
    ],
    youxie: [".*", ".*", ".*", ".*", ".*", ".*", ".*"],
  },
  {
    name: "Classic Game",
    code: "5f3df1f28d20f",
    heng: [
      "[RESOURCE\\s]+",
      "[DEVELOPMENT]+",
      "[YEARS]{2}(OF|\\s|PL|EN|TY)+",
      "[^SEVEN_ROLLED]+",
      "[GRAIN]+[^ORE]",
    ],
    zuoxie: [
      "[C-I]T[IE\\s]",
      "[LONGEST][ROAD]*[TOKEN]",
      "[LUMBER]*(CA|RD|\\s)+",
      "[COAST]+(\\W|AT|ER)",
      "[^ROBBER][DESERT]+",
    ],
    youxie: [
      "[LARGE\\sT]+[ARMY]+",
      "[VICTORY_POINTS]+",
      "[TRADE\\s]+",
      ".{2}[^COMPETITION]+",
      "([FEILD\\s])+\\1",
    ],
  },
  {
    name: "Consciousness transfer pioneer",
    code: "5a49fd72e6a6d",
    heng: [
      "(?!.*([^ ])\\1.*)[NANO][YSZH]+",
      "([AEIOU])(\\w)\\2([AEIOU])",
      "(?!.*([^ ])\\1.*)S.*[REAL]?",
    ],
    zuoxie: [
      "[EIOU][RUPERT]+",
      "(?!.*([^ ])\\1.*).*[M-R][K-Y]",
      "[YOUR]*[SOUL]?",
      "[MAN?]+",
    ],
    youxie: [
      "[SPIRA]+[^OF THINGS]",
      "[ZL]+[KNOWLEDGE]+",
      "[ROY2]+",
      "[TRANSPARENCY]?[HD-EEG]+",
    ],
  },
  {
    name: "Undone by the barista",
    code: "5e0e70f516316",
    heng: [
      "P?(L|AN|E)*",
      "[IN\\sCASE]*",
      "[THE]SU?PR[EME\\sLEADER]",
      "([SEEKS])\\1[TO]\\1",
      "[FLEE]*",
    ],
    zuoxie: [
      "[SAFELY]*",
      ".[ROLL|OUT]*",
      "(SL|EE)P[ER\\sAGENTS]*",
      "[AL]+[SO]*",
      "(PRE)|[PARE\\sA]*",
    ],
    youxie: [
      "[SEND]*A?",
      "[CLASS]*",
      "(FO|UR)[SPY]*",
      "[TO]*|[ISRAEL]*",
      "([EMIGRATE])\\s\\1",
    ],
  },
  {
    name: "KTest",
    code: "5dc5dcff5b6b1",
    heng: [
      "^[^P|E|D|G|\\s][ZXC]?[B|E]*E$",
      "^[K-Y]{1}\\SS?[TRD]{1}",
      "\\b[NXC]{1}\\.?[LIS]{2}[DNO]{2}\\b\\S?",
      "^F[CPG]{3}.?\\s*",
      ".?K*^A{1}[^A-IK-Z]+[TEST]{1}$\\b",
    ],
    zuoxie: [
      "^[DIM]+[CCC]+[^SENA]$",
      "\\.?[TOM]{1}[^DOM]\\W?G+[JUICE]{1}",
      "\\W?^\\w{2}L+(T|A|P){2}$\\s*",
      "^[^C-Z]+[IO]{2}[^\\s]$",
      "^(M|P)[^\\s]T?(N|P)+",
    ],
    youxie: [
      "\\b[FNAZ]+\\b",
      ".?\\b\\w{2}[PI]+\\b",
      ".?^[KROT]{1}[LG]+[MOON]{2}\\b",
      "\\b.+[CLONE]+[POST]+B\\b$",
      "[^O]{1}\\w{2}.?$",
    ],
  },
  {
    name: "Final minipuzzle",
    code: "5eac34bd09565",
    heng: [
      "(N|E|W)",
      "[A-S][H-K]",
      "T(E)(A|R)",
      "(\\-|\\?)(I*N)(\\-|\\!)",
      "F+(OR)|(TRA)*(N\\!)*",
      "(TOO)*E(A)*S*Y*(\\?)*",
      "[t-zT-Z]",
    ],
    zuoxie: [
      "\\-(TXT|OR\\?|RST)",
      "[RIGHT]NO[AEIOU]",
      "[AEIOU]*(F|I|N|E)",
      "(DRQS)|[U-Z](RT)(\\-|\\\\)",
    ],
    youxie: [".*", ".*", ".*", ".*"],
  },
  {
    name: "On such a winter's day",
    code: "5a6f2dd78baec",
    heng: [
      "[CAPO&4]+",
      "(LA|ST|IN|FI|RS|T |OU|T )?[LF0-3]+",
      "[NR]+\\d{2}[DAY]",
      "[REAL]{2}[M4]+",
      "[DREAM1NG]+",
    ],
    zuoxie: [
      "([D\\.OMG]+)",
      "([0-3][3-5][4-6][F-Z])",
      "..(.).(\\1)",
      ".*",
      "[^BROWN][RL]+",
    ],
    youxie: [
      "\\d(.)\\1",
      "[EN]+[LEAVES]",
      "(?=..(.)\\1\\W)[G E&11 E7 E&4]+",
      "[M4F]+[CHURCH]+",
      "(?=.*0.*)[DREAM]\\d{2}",
    ],
  },
  {
    name: "Melody transmission to Love and Freedom",
    code: "5de7e3c50b33e",
    heng: [
      "(?=.*(.+)\\1)-*[+-/]+-*",
      "(?!.*([A-Z]).*\\1)-*[^QUIHK\\-SOU¿DY]+-*",
      "-+[^QUICK\\-SKINAR⊙LNE]{2}-+",
      "(?=.(.)Q.\\1.)-*[^KEN KWEZY÷SOX]+[^COME♡CLOSER]+-*",
      "(?=(.)...\\1)-*[SPEAKERS]+I[EYES]+-*",
    ],
    zuoxie: [
      "-*D.*-*",
      "(?=\\w\\W\\w.)-*[IET\\-]+-*",
      "-[E-I]+[EU]+.*-*",
      "-*N[OQ]+KX?-*",
      "(?=(.)A\\1..)-*[SAIS\\-]+-*",
      "(?=(.)(.)\\1\\2)-*.*-*",
      "(?=(.).\\1).-*P.*-*",
    ],
    youxie: [
      "(?!.*(.).*\\1)[SLOWLY\\-]*",
      "(?!.*(.).*\\1.*)[PIK\\-]+.*",
      "(?!.*([^\\-]).*\\1.*)[LIQUID SHINY\\-]+.*",
      "[AEiOU\\-]+.*",
      "-*[SPACE][FIN\\-]+-*",
      "[AWK]?(?=.(.).\\1)-*[SED\\-]+-*",
      "-*[TXFR\\-]-*",
    ],
  },
  {
    name: "Binary Bee",
    code: "56f2d8917b8ba",
    heng: ["[01]*[10]*", "(.).\\1", ".?0?.?"],
    zuoxie: [".*1*.", "0*?0*?1*?0*?0*?", "(.)\\1"],
    youxie: ["(.*)\\1", "(0)\\1(1)?", "00|11|01|10"],
  },
  {
    name: "Beginnings",
    code: "56bd02e7b0721",
    heng: ["[A-N]+D?", "L(.)[^L-P]\\1", "[REALLY?]+[DUH]?"],
    zuoxie: ["O?D?D?", "([LIST])[WOW]\\1", "[E-GO-U]*[ROT]", "[HOT][LINE]"],
    youxie: ["[REAL][LIFE]", "...", "[DOWN]+[UNDER]+", "L?O?L?"],
  },
  {
    name: "Danger",
    code: "57ac7f608fcb4",
    heng: ["[☞-⚡]*"],
    zuoxie: ["(?!\\u2621)[A-☡]"],
    youxie: ["[^☟⚡☞⚡]*"],
  },
  {
    name: "Invisible danger",
    code: "59c20c7fc85b4",
    heng: ["[DELERIANT]*Y.*", "[ATROPINE]*T+(?!☢).*N*", "S[CORPOLAMINE]*.*A"],
    zuoxie: ["N[^VX]", "\\W[☢-☤].", "[HAZYMAT]*"],
    youxie: ["[SARIN].*.", "[ANTHRAX]+(?!☤)..", "[TABUN]*\\u2006"],
  },
  {
    name: "Peace",
    code: "5689c51256c02",
    heng: ["([A-Z]|3)[ -!]", "[A-G]\\d(E|F)", "[RIDE:][Z-\\[]"],
    zuoxie: ["(E|6)(AC|Z|ED)", "\\W\\d?[RA]+\\??", "(\\W|\\d)[B-D]"],
    youxie: ["[D-Z]+", "Z(\\d|\\w)\\1", ".?[!%:]+"],
  },
  {
    name: "De Saison (Corrected)",
    code: "5a43f422b1666",
    heng: ["(B.N|.+Y)", "L?A?E?(U|P)[N-X]+", ".E(S|L)"],
    zuoxie: ["[K-N]{2}", "[XY]+[EF]", "(O)[^X]\\1", "(M|J)(E|T)"],
    youxie: ["(SU|.E)", "[EU]{2}R?J?", "(FET)?(LX)O?", "[QNU][IMY]"],
  },
  {
    name: "Nokia T-Shirt 2018",
    code: "5a4fc05079362",
    heng: ["\\D+", "[IJ-NO]*?", "[\\101-\\117]+", "[0-8]{3,4}\\D?", "\\W+"],
    zuoxie: [
      "(a7;|A8;)",
      "(N|U)[ZIJN]\\d\\W",
      "([^0-9A-Z]).K.\\{",
      "\\{([O])\\1\\d",
      "\\.[\\x4a-\\x4e]{2}",
    ],
    youxie: [
      "\\{[92][mN]",
      ".*?\\}0O?J",
      ";1;?\\S{2}\\W",
      "(7|8)(\\x49)\\2\\{",
      "AA?N?\\}",
    ],
  },
  {
    name: "Wunsch",
    code: "5aeccfd7aa4f9",
    heng: ["[ZIEH HER!]*", "[du+ich= <3 ]*", "[HDGDL!]*"],
    zuoxie: ["[HDL +-]*", "[DU+ICH]*", "[KOMM HER]*"],
    youxie: [
      "[^Doppelseitenlöscher3000].*",
      "[DAS:A+O!].[HAJO!]",
      "[DAS W|RD SCHOEN]*",
    ],
  },
  {
    name: "Swag Hunt Puzzle",
    code: "5e3c5f9991a79",
    heng: [
      "(WC|LO|A|T)+[0-9]*",
      "[BIKLOTX]*",
      "[ADEST]*",
      "(SK|TO|AT)+[13579]*",
      "[0-5]*[ABCEF]",
    ],
    zuoxie: [
      "E[0-5]*[DEF]*",
      "(ID|AT|BE)[0189]{2}",
      "[0-9]*.*T.*[24567]+",
      "[ACOS]*",
      "[BSW]*",
    ],
    youxie: [
      "[13579]*S*",
      "0[ABK]+",
      "[BDF]+[0-3]*[EROTW]+",
      "[24567]*[CDX]*",
      ".*4",
    ],
  },
  {
    name: "Sample Puzzle",
    code: "59e76811836a3",
    heng: ["[AS]*", ".*", "(MX|LP)"],
    zuoxie: ["(.).*\\1", ".*", "[SE]*"],
    youxie: ["[^S]*", ".*X.*", "[ARP]*"],
  },
  {
    name: "On The Radio (EASY)",
    code: "5a858d2e48af5",
    heng: [
      "[RUSH]",
      "[CHICAGO]*",
      "[EMERSON]*[LAKE]&[PALMER]",
      "[JETHRO][TULL]*",
      "[ELVIS]",
    ],
    zuoxie: [
      "[LYNYRD SKYNYRD]*",
      "[ERIC BURDON & THE ANIMALS]*",
      "[JOE COCKER]*",
    ],
    youxie: ["[PINK FLOYD]*", "[HALL]&[OATES]*", "[CCR]*"],
  },
  {
    name: "Only_lookaheads_(simple)",
    code: "5c8e7fb04956f",
    heng: ["(?=\\w)(?!\\d)(?!.?[^;<_>{-}].?).?"],
    zuoxie: ["(?!.?[G-L])."],
    youxie: ["(?![N-Pa-z]).?(?=[^A-Z]).?"],
  },
  {
    name: "blue-rabbit",
    code: "5a48e221e6651",
    heng: ["\\D+", "[IJ-NO]*?", "[\\101-\\117]+", "[0-8]{3,4}\\D?", "\\W+"],
    zuoxie: [
      "(a7;|A8;)",
      "(N|U)[ZIJN]\\d\\W",
      "([^0-9A-Z]).K.\\{",
      "\\{([O])\\1\\d",
      "\\.[\\x4a-\\x4e]{2}",
    ],
    youxie: [
      "\\{[92][mN]",
      ".*?\\}0O?J",
      ";1;?\\S{2}\\W",
      "(7|8)(\\x49)\\2\\{",
      "AA?N?\\}",
    ],
  },
  {
    name: "super powers",
    code: "5afbde1096ac4",
    heng: [
      "[A-D,O-Z][E-L][A-D,O-Z]|[E-L][A-D,O-Z][E-L]",
      ".{2}(MA|PO|SE)",
      "[A-P]*",
    ],
    zuoxie: [".*", "[OST].I?U?V?", "LEG|ARM", "CN|HN"],
    youxie: ["GN|AE", ".*", "[CRST]M?L*U?", "[AMPC][AEIOU]"],
  },
  {
    name: "Easy bee",
    code: "5d8483e52fe5f",
    heng: ["[BEE|WASP].[^SOUP]", "[ALPINOBOMBUS!][B][^BE]!", "..[BEE]"],
    zuoxie: ["![HONEY]", "[^B][BUMBLE]*", "^[U][B][B]", "[BOMBINI]!"],
    youxie: ["[BEE!]*", "[EEE][^FLYSPRAY].", "[^HUMMM]+[BUZZ]", ".[BOMBUS]"],
  },
  {
    name: "Botany",
    code: "5d7f9181be88a",
    heng: ["[KAURI]+", "[\\[\\s]+[CONE\\s\\]]{3}", "[AUST][R][ALIA]+"],
    zuoxie: [
      "[BUNYA\\s]*",
      "[PINUS\\]]*",
      "[ARAUCANA]*",
      "[\\[ERA]*",
      "[P1NALE\\s]*",
    ],
    youxie: [
      "[SAUROPOD]\\s",
      "[\\[KAURI]*",
      "[JURaSSIC]*",
      "[A][RAUCARI\\]][A]",
      "[\\sAUROPOD]*",
    ],
  },
  {
    name: "Syncron",
    code: "5d8ca296764d0",
    heng: [
      ".A.",
      "[COSMOPOLITAN]+",
      "[WAR\\sZAWA]+",
      "[BEST][SYNCRON]+[IT]",
      "[JOB][TWARDA4]*",
    ],
    zuoxie: ["[^A-Y]I.", "[D-K][B-R]{2}.", ".*MN.*", "(.)\\1\\s.", "(KPA){1}"],
    youxie: [
      "[AEIOUY]*",
      "(NE|WS)\\s.",
      "(.)[WIN]+\\1.",
      "[WIN].*",
      "\\S[FIKA].",
    ],
  },
  {
    name: "Sun destination",
    code: "587029fc8ed67",
    heng: ["[CIGAR]", "[RUM][CARIBBEAN]", "[CORAL]"],
    zuoxie: ["[BIKINI][SAND]", "[TROPICS][SURFBOARD]"],
    youxie: ["[PALM TREE][SUN]", "[BEACH][OCEAN]"],
  },
  {
    name: "Talupema",
    code: "579d798f5235f",
    heng: ["[LIN]", "[ABC].*", "[GINU]{3}", ".*[AILNUTS]", "[DOSA]"],
    zuoxie: ["[H-K][^D-P][^A-Q]", "[^AI]NT", "[GOLD][^BC][AUS]"],
    youxie: [".*", "[A-L]N[A-G]", "[D-J][IG][^M]"],
  },
  {
    name: "Hydroponics for beginners",
    code: "5d84a0a71c302",
    heng: ["[POLLEN]+", "[FURROW\\s]+", "[GREW]+"],
    zuoxie: ["[WATER]+", "[ROSE\\s]+", "[ALFALFA]+"],
    youxie: ["[FROST]+", "[PETAL\\s]+", "[H2WO]+"],
  },
  {
    name: "Hex-Hex",
    code: "5e2287249f2cb",
    heng: [
      "[&-^][%-}][)-^][(-[]['-[][%-~][ -\\\\]",
      '[.-`][+-^][ -~][)-\\\\]["-\\\\][.-|][)-~][)-}]',
      "[ -[]['-\\]][)-_][*-|][.-`][,-|][&-[]",
    ],
    zuoxie: [
      "[^\\x47-\\x7e][^\\x46-\\x5c]",
      "[^\\40-\\104][^\\50-\\104][^\\53-\\103]",
      "[^\\44-\\104][^\\x46-\\x7d][^\\x31-\\x61]",
      "[^\\46-\\105][^\\41-\\101][^\\51-\\102]",
      "[^\\x47-\\x5c][^\\50-\\103][^\\50-\\103]",
      "[^\\50-\\57][^\\40-\\100][^\\46-\\100]",
      "[^\\x44-\\x7e][^\\52-\\104][^\\40-\\101]",
      "[^\\45-\\100][^\\55-\\103]",
    ],
    youxie: [
      "[^\\x43-\\x5c][^\\x45-\\x61]",
      "[^\\x42-\\x5e][^\\x46-\\x5f][^\\x42-\\x5f]",
      "[^\\x45-\\x60][^\\x42-\\x7e][^\\44-\\102]",
      "[^\\x44-\\x7d][^\\x45-\\x5d][^\\x31-\\x5f]",
      "[^\\55-\\57][^\\x43-\\x5d][^\\47-\\105]",
      "[^\\x45-\\x7d][^\\55-\\104][^\\x47-\\x5c]",
      "[^\\45-\\104][^\\x46-\\x7e][^\\x46-\\x7e]",
      "[^\\50-\\105][^\\x46-\\x5d]",
    ],
  },
  {
    name: "Seven",
    code: "5a77adb6e54b9",
    heng: ["(?=\\d)25", "[^1346-9]+", "^2[^0-46-9]$"],
    zuoxie: ["[\\x32\\x35]+", "5\\u0030\\d", "(?!a-z)(?=2)\\d[A-Z]{0}5"],
    youxie: ["[a|2|d|4|f]+[^\\u0032]", "[\\s]{0}[1-5]{1}[0-4]{1,2}", "^25$"],
  },
  {
    name: "The One",
    code: "5d767da3bc335",
    heng: ["((?![A-D])[A-Z])(?!0|[2-9])\\d"],
    zuoxie: ["(?!0|[2-9])\\d", "(?![A-I]|[K-Z])\\w"],
    youxie: ["(?![E-I])[A-Z]", "[0-9]+"],
  },
  {
    name: "Animal",
    code: "5ad150aab613b",
    heng: ["[B-E].*"],
    zuoxie: ["(85|E?|P?|J*|DOS)", "[^a-z\\d\\sA-BA-DF-Z_]", "[A-C].*"],
    youxie: ["[DBZ2].*", ".?.*\\w", "[^aAJPp]"],
  },
  {
    name: "Find a tour",
    code: "56c5c1cb2c33c",
    heng: ["[KUBA]*", "(KA|AK)", "[S-Z]"],
    zuoxie: ["[KUBA]+", "[A-H]{0,100}"],
    youxie: ["", "[^TAR][^RAT]"],
  },
  {
    name: "Yr12 Christmas Quiz 3",
    code: "5fd91a0dcb8ae",
    heng: ["[^D-Q]+", "[SACK]+", "[PRESENT]+"],
    zuoxie: ["[COOKER]+", "[RICE]+", "CA|ND|LE"],
    youxie: ["[AEIOU]+", "[CR3SC3NT]+", "[^A-JL-QS-Z]+"],
  },
  {
    name: "i/o",
    code: "5749b91f18b12",
    heng: ['^.[!")]?[@;]?O$'],
    zuoxie: [".*", "I.*(IN){0,5}\\1*"],
    youxie: ["[^do]*G{0}.*I", ".*"],
  },
  {
    name: "Bling",
    code: "56ab2b8e5ce56",
    heng: ["(\\$[-1]?)$"],
    zuoxie: ["^[\\d]?(\\W)$"],
    youxie: ["(CA$H)?\\$$"],
  },
  {
    name: "Super Hard Puzzle",
    code: "5b04135d65b20",
    heng: ["(WOW)", "(THAT)", "(WASNT)", "(HARD)", "(YAY)"],
    zuoxie: ["(TDY)", "(TNRA)", "(WASAY)", "(OHAH)", "(WTW)"],
    youxie: ["(YHW)", "(AAAT)", "(YRSHW)", "(DNAO)", "(TWO)|(T{2}W)"],
  },
  {
    name: "The obnoxiously easy puzzle.",
    code: "57198458c5af2",
    heng: ["A"],
    zuoxie: ["A"],
    youxie: ["A"],
  },
  {
    name: "Trial Challenge #1 - Basic Trials Crosswords",
    code: "5d768f5bbda33",
    heng: ["[^B]"],
    zuoxie: ["[^A]"],
    youxie: ["C+"],
  },
  {
    name: "Trial Challenge #3 - Advanced Trials Crosswords",
    code: "5d76ac7227b9f",
    heng: ["[^ABC]"],
    zuoxie: ["[^CDE]"],
    youxie: ["(A|F)"],
  },
  {
    name: "League Challenge #1 - Preliminary Round 1",
    code: "5d75e946035fc",
    heng: ["AC"],
    zuoxie: ["[^AB]", "(A|C)"],
    youxie: ["[^BC]", "C+"],
  },
  {
    name: "Trial Challenge #2 - Intermediate Trials Crosswords",
    code: "5d768fdb99ac9",
    heng: ["[^F]"],
    zuoxie: ["[^G]"],
    youxie: ["(E|G)"],
  },
  {
    name: "Definitely not an analysis aid",
    code: "5dc881800621c",
    heng: [
      "(Y0)?A*",
      "(Y1)?A*",
      "(Y2)?A*",
      "(Y3)?A*",
      "(Y4)?A*",
      "(Y5)?A*",
      "(Y6)?A*",
    ],
    zuoxie: [
      "(X7)?A*",
      "(X6)?A*",
      "(X5)?A*",
      "(X4)?A*",
      "(X3)?A*",
      "(X2)?A*",
      "(X1)?A*",
      "(X0)?A*",
    ],
    youxie: [
      "(Z0)?A*",
      "(Z1)?A*",
      "(Z2)?A*",
      "(Z3)?A*",
      "(Z4)?A*",
      "(Z5)?A*",
      "(Z6)?A*",
      "(Z7)?A*",
    ],
  },
  {
    name: "League Challenge #3 - Preliminary Round 3",
    code: "5d767144d06eb",
    heng: ["MP"],
    zuoxie: ["(P|M)", "[^NO]"],
    youxie: ["M+", "P+"],
  },
  {
    name: "League Challenge #2 - Preliminary Round 2",
    code: "5d75ebeee6f42",
    heng: ["ML"],
    zuoxie: ["(M|L)", "[^LIP]"],
    youxie: ["M+", "[^MIP]"],
  },
  {
    name: "League Challenge #4 - Preliminary Round 4",
    code: "5d767610c85f0",
    heng: ["UE"],
    zuoxie: ["[^CD]", "[^ST]"],
    youxie: ["U+", "E+"],
  },
];
